### ISSUE TITLE
The permissions requested by this app are way over the top

### ISSUE THREAD

**Issue by guntbert** [despo/issuehub.io#218]
When attempting to log in via github I am presented with a shocking list of permissions

> This application will be able to read and write all public and private repository data. This includes the following:
    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
    Collaboration invites

Why do you need them?

**Comment by despo** [comment]
If you choose to login issuehub enables you to filter your private repositories as well as public ones. However, I don't believe that their API offers more specific scopes but I could be missing something. If you know how to resolve this I would be happy to merge a relevant PR.

https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

**Comment by pmav99** [comment]
There is the `repo` scope which `Grants full access to private and public repositories.`
and there is the `public_repo` scope which `Limits access to public repositories`
https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes
