### ISSUE TITLE
Search issues in my github starred repositories

### ISSUE THREAD

**Issue by alexkubica** [despo/issuehub.io#328]
Hi, I'd like to use the website to search within my github starred repositories to find issues only in repositories that I'm interested in.
Let me know how does it sound and if you're up to it I'll give it a try 😄

**Comment by despo** [comment]
Hi @alexkubica - the problem with this is that this project is a simple wrapper around a github request with no persistence and to achieve that it would require issuing multiple requests - one to retrieve all starred repositories and then one for each repository. I would rather not add such a complex feature to this codebase.

**Comment by alexkubica** [comment]
I think it might be useful for many open source contributors so just think about it, but if you decide not do it after all I understand completely.
It's your call! I'm closing this issue for now.
