### ISSUE TITLE
Less used languages not showing

### ISSUE THREAD

**Issue by fenollp** [despo/issuehub.io#52]
Hi,

I love the idea of putting issues at the center, instead of projects!
However I am not able to find any issues for Erlang projects.

Is issuehub.io not parsing these?

**Comment by despo** [comment]
Hi @fenollp.

Thank you.

Issuehub is not doing any processing on github's api so it should also work for erlang.

It does work for me. Try this url http://issuehub.io/?label%5B%5D=bug&language=erlang
You have to pick at least one label for the request to be processed.

Let me know if you are still experiencing this issue or if this is ok to close.

**Comment by fenollp** [comment]
Ah! Thanks @despo I think it's just the colours on the labels that were weird for me (I'm colourblind).
Maybe select a label by default?
