### ISSUE TITLE
Easy Pick Label suggestion

### ISSUE THREAD

**Issue by patkar** [despo/issuehub.io#57]
Easy pick is always a label for contribution beginners. May take care of alternations like `easypick`, `easy-pick` and `Easy Pick`.

**Comment by jenkoian** [comment]
+1

Examples: https://github.com/puli/issues/labels/Easy%20Pick, https://github.com/symfony/symfony/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+Pick%22

**Comment by tegon** [comment]
I've added a PR for this: https://github.com/despo/issuehub.io/pull/62
