### ISSUE TITLE
White-space:no-wrap is causing buttons to fall out of view on mobile

### ISSUE THREAD

**Issue by georgiaobrien** [despo/issuehub.io#71]
white-space: no-wrap on checkboxes div is causing buttons to fall off the page on mobile. Can be fixed by changing to normal, then making checkbox div class 'large-6' and language div class 'large-1' to give checkbox div more space. There is also a BR that needs removing.
![img_1862](https://cloud.githubusercontent.com/assets/11182042/11607888/6df6ba90-9b50-11e5-8968-a16503e754cb.PNG)

**Comment by pamungkaski** [comment]
hi @despo @georgiaobrien 
I think this issue fixed by #73 , and i think it should be closed by now
