### ISSUE TITLE
Label suggestions

### ISSUE THREAD

**Issue by leotm** [despo/issuehub.io#80]
[`starter`](https://github.com/search?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22starter%22&type=Issues&ref=searchresults)
[`good first bug`](https://github.com/search?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22&type=Issues&ref=searchresults)
[`easy fix`](https://github.com/search?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22easy+fix%22&type=Issues&ref=searchresults)
[`new contributor`](https://github.com/search?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22new+contributor%22+&type=Issues&ref=searchresults)

**Comment by shivasheeshyadav** [comment]
Hey @leotm ,
I'll work on this issue. Please add "hacktoberfest" label to this issue.

**Comment by leotm** [comment]
Hey @shivasheeshyadav ,
Happy to, but I think only the repo owner can?
Just had a quick read [this](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/ ) and [this](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/).

**Comment by shivasheeshyadav** [comment]
Ok @leotm .
@despo I'll work on this issue. Please add "hacktoberfest" label to this issue, and assign it to me.

**Comment by despo** [comment]
Closing as #143 addreses adding more beginner friendly labels.
