### ISSUE TITLE
Label suggestion

### ISSUE THREAD

**Issue by PeterDaveHello** [despo/issuehub.io#84]
`BEGINNER` :)
-> https://github.com/search?utf8=%E2%9C%93&q=state%3Aopen+label%3ABEGINNER&type=Issues

**Comment by pablopunk** [comment]
@PeterDaveHello This is [already](http://issuehub.io/?label%5B%5D=beginner&language=) a label in issuehub

**Comment by PeterDaveHello** [comment]
oops, thanks @pablopunk !
