### ISSUE TITLE
Exclude pull requests

### ISSUE THREAD

**Issue by jayvdb** [despo/issuehub.io#89]
https://github.com/nltk/nltk/pull/1669 is currently included because it is labeled `tests`.
Pull requests are not issues :P

**Comment by bekicot** [comment]
@jayvdb Pull Request is an issue, as far as github concerned. 
> Note: In the past, pull requests and issues were more closely aligned than they are now. As far as the API is concerned, every pull request is an issue, but not every issue is a pull request.

> This endpoint may also return pull requests in the response. If an issue is a pull request, the object will include a pull_request key.

https://developer.github.com/v3/issues/

Not sure we can request only `issues` that is not a pull_request. but we can definitely filter it.

**Comment by jayvdb** [comment]
From user of issuehub.io perspective, looking to work on unallocated problem, a PR is not helpful.
Yes, they should be filtered out.  Perhaps hidden by a user-selected filter which is enabled by default.

**Comment by despo** [comment]
Resolved :shipit:
